export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL;

export enum OperationType {
    CAFE_GRANULOMETRIE = "CAFE_GRANULOMETRIE",
    CAFE_DEFECTUOSITE = "CAFE_DEFECTUOSITE",
    CAFE_OLFACTIF = "CAFE_OLFACTIF",
    CACAO_COUPES_FEVES = "CACAO_COUPES_FEVES",
    CACAO_GRAINAGE = "CACAO_GRAINAGE",
    CACAO_TAUX_COQUE = "CACAO_TAUX_COQUE",
    CACAO_SENSORIELLE = "CACAO_SENSORIELLE",
    TENEUR_CACAO = "TENEUR_CACAO",
    TENEUR_CAFE = "TENEUR_CAFE",
    TENEUR = "TENEUR",
    ECHANTILLONNAGE_CACAO = "ECHANTILLONNAGE_CACAO",
    ECHANTILLONNAGE_CAFE = "ECHANTILLONNAGE_CAFE",
    ECHANTILLONNAGE = "ECHANTILLONNAGE",
    INSPECTION = "INSPECTION",
    FICHE_TEST = "FICHE_TEST",
}

export const constants = {
  api: {
    baseUrl: API_BASE_URL,
    uploadsUrl: `${API_BASE_URL}/api`,
  },
  categories: [
    {
      title: "Cacao",
      slug: "cacao",
      actions: [
        {
          id: OperationType.INSPECTION,
          label: "Inspection",
          icon: "magnify",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.ECHANTILLONNAGE_CACAO,
          label: "Échantillonnage",
          icon: "flask-outline",
          type: "photo",
          requireNumLot: false,
        },
        {
          id: OperationType.CACAO_SENSORIELLE,
          label: "Analyse sensorielle",
          icon: "scent",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.CACAO_COUPES_FEVES,
          label: "Analyse coupe de fèves",
          icon: "content-cut",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.CACAO_GRAINAGE,
          label: "Analyse grainage",
          icon: "chart-bubble",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.CACAO_TAUX_COQUE,
          label: "Analyse taux de coques",
          icon: "nut",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.TENEUR_CACAO,
          label: "Taux d’humidité",
          icon: "water-percent",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.FICHE_TEST,
          label: "Fiches test",
          icon: "file-document-edit-outline",
          type: "form",
          requireNumLot: false,
        },
      ],
    },
    {
      title: "Café",
      slug: "cafe",
      actions: [
        {
          id: OperationType.INSPECTION,
          label: "Inspection",
          icon: "magnify",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.ECHANTILLONNAGE_CAFE,
          label: "Échantillonnage",
          icon: "flask-outline",
          type: "photo",
          requireNumLot: false,
        },
        {
          id: OperationType.CAFE_DEFECTUOSITE,
          label: "Analyse défectuosité",
          icon: "alert-outline",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.CAFE_GRANULOMETRIE,
          label: "Analyse de granulométrie",
          icon: "sieve",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.CAFE_OLFACTIF,
          label: "Analyse olfactive",
          icon: "scent",
          type: "photo",
          requireNumLot: true,
        },
        {
          id: OperationType.TENEUR_CAFE,
          label: "Évaluation teneur",
          icon: "scale-balanced",
          type: "photo",
          requireNumLot: false,
        },
        {
          id: OperationType.FICHE_TEST,
          label: "Fiches test",
          icon: "file-document-edit-outline",
          type: "form",
          requireNumLot: false,
        },
      ],
    },
  ],
};